[package]
name = "linked-sql-macros"
version = "0.1.0"
edition = "2024"

description = "Procedural macros for the linked-sql"
license = "MIT"

[lib]
proc-macro = true

[dev-dependencies]
pretty_assertions = "1"

[dependencies]
case = "1.0.0"
proc-macro-error = "1.0.4"
convert_case = "0.8.0"
proc-macro2 = "1.0.33"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full", "visit", "visit-mut", "extra-traits"] }

[features]
default = []
experimental_id_trait = []
inventory = []
serde = []
